version: '3'
services:
  webapp:
    build: webapp
    restart: always
    working_dir: /app
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    links:
      - db
    depends_on:
      - db
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: "shop-upgrade"
      POSTGRES_PASSWORD: "shop-upgrade"
      POSTGRES_DB: "shop-upgrade"
    ports:
      - "5432:5432"
